import type { Metadata } from "next";
import { Comfortaa, Geist } from "next/font/google";
import "./globals.css";
import MenuBar from "../components/MenuBar";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Comfortaa({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: '400',
});

// const geistMono = Comforter_Brush({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">{children}
        <MenuBar/>
        </body>
    </html>
  );
}
